name: luacheck

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@main

      - uses: lunarmodules/luacheck@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
